name: queen_themes
description: queen support for multiable themes
version: 0.0.3
# homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  provider: ^6.0.1
  shared_preferences: ^2.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
